#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Froxlor\Command\BindSlaveConfigurationCommand;

require_once 'bootstrap.php';

$application = new Application();
$application->add(new BindSlaveConfigurationCommand());
$application->run();
