#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require_once 'bootstrap.php';

$application = new Application();
$application->add($container->get('cmd_bindSlaveConfiguration'));
$application->run();
